export const TimeIncrements = {

  amTimes: [
    { time: '12:00', am: true, pm: false },
    { time: '12:30', am: true, pm: false },
    { time: '1:00', am: true, pm: false },
    { time: '1:30', am: true, pm: false },
    { time: '2:00', am: true, pm: false },
    { time: '2:30', am: true, pm: false },
    { time: '3:00', am: true, pm: false },
    { time: '3:30', am: true, pm: false },
    { time: '4:00', am: true, pm: false },
    { time: '4:30', am: true, pm: false },
    { time: '5:00', am: true, pm: false },
    { time: '5:30', am: true, pm: false },
    { time: '6:00', am: true, pm: false },
    { time: '6:30', am: true, pm: false },
    { time: '7:00', am: true, pm: false },
    { time: '7:30', am: true, pm: false },
    { time: '8:00', am: true, pm: false },
    { time: '8:30', am: true, pm: false },
    { time: '9:00', am: true, pm: false },
    { time: '9:30', am: true, pm: false },
    { time: '10:00', am: true, pm: false },
    { time: '10:30', am: true, pm: false },
    { time: '11:00', am: true, pm: false },
    { time: '11:30', am: true, pm: false }
  ],
  pmTimes: [
    { time: '12:00', am: false, pm: true },
    { time: '12:30', am: false, pm: true },
    { time: '1:00', am: false, pm: true },
    { time: '1:30', am: false, pm: true },
    { time: '2:00', am: false, pm: true },
    { time: '2:30', am: false, pm: true },
    { time: '3:00', am: false, pm: true },
    { time: '3:30', am: false, pm: true },
    { time: '4:00', am: false, pm: true },
    { time: '4:30', am: false, pm: true },
    { time: '5:00', am: false, pm: true },
    { time: '5:30', am: false, pm: true },
    { time: '6:00', am: false, pm: true },
    { time: '6:30', am: false, pm: true },
    { time: '7:00', am: false, pm: true },
    { time: '7:30', am: false, pm: true },
    { time: '8:00', am: false, pm: true },
    { time: '8:30', am: false, pm: true },
    { time: '9:00', am: false, pm: true },
    { time: '9:30', am: false, pm: true },
    { time: '10:00', am: false, pm: true },
    { time: '10:30', am: false, pm: true },
    { time: '11:00', am: false, pm: true },
    { time: '11:30', am: false, pm: true }
  ]
}
